site_name: 5GMETA
nav:
    - Getting Started: getting-started.md
    - Consuming Guide: consuming-guide.md
    - Dataset Guide: datasets.md
    - Producing Events Guide: producing_events_guide.md
    - Data Processing Tutorials: tutorial-processing.md
    - About: about.md
theme: readthedocs
