site_name: 5GMETA
nav:
    - Home: index.md
    - Message Data Broker: message-databroker.md
    - Data Producers (ActiveMQ): activemq-example.md
    - Stream Data Gateway: stream-datagateway.md
    - Stream Data Gateway Examples: stream-example.md
    - Avro Events Producer Example: stream-avro-producer.md
    - About: about.md
    - Consuming guide: consuming-guide.md
    - Producing events guide: producing_events_guide.md
    - Dataset guide: datasets.md
theme: readthedocs
