site_name: 5GMETA
nav:
    - Home: index.md
    - Consuming Guide: consuming-guide.md
    - Dataset Guide: datasets.md
    - Producing Events Guide: producing_events_guide.md
    - Advanced Concepts:
        - Message Data Broker: message-databroker.md
        - Stream Data Gateway: stream-datagateway.md
        - Stream Data Gateway Examples: stream-example.md
        - Avro Events Producer Example: stream-avro-producer.md
    - FAQ: FAQ.md
    - About: about.md
theme: readthedocs
